export const FETCH_EMP_DETAILS = 'FETCH_EMP_DETAILS';
export const FETCH_EMP_DETAILS_SUCCESS = 'FETCH_EMP_DETAILS_SUCCESS';
export const FETCH_EMP_DETAILS_FAILED = 'FETCH_EMP_DETAILS_FAILED';

export const SEARCH_EMP_DETAIL = 'SEARCH_EMP_DETAIL';
export const SEARCH_EMP_DETAIL_SUCCESS = 'SEARCH_EMP_DETAIL_SUCCESS';
export const SEARCH_EMP_DETAIL_FAILED = 'SEARCH_EMP_DETAIL_FAILED';